### ISSUE TITLE
Can you please tell me how to replace image-resize-stream with gm (GraphicsMagick)

### ISSUE THREAD

**Issue by luofan189** [bredikhin/skipper-thumbnail#1]
Hi,

Would like to replace image-resize-stream with gm for my sails app as image-resize-stream has a very complex dependencies, but have no clue how to do this. Could you please help me on this?

Thanks a lot!

**Comment by bredikhin** [comment]
Take a look here: http://stackoverflow.com/questions/24069203/skipper-in-sailsjs-beta-image-resize-before-upload/24189660#24189660.

**Comment by luofan189** [comment]
Do you have an example which uses skipper-s3 rather than skipper-disk? Thanks!

**Comment by bredikhin** [comment]
Should be more or less the same, try piping thumbnail to an S3 receiver instead of disk here https://github.com/bredikhin/sailsjs-skipper-thumbnail-example/blob/master/api/controllers/ImageController.js#L16. Feel free to post your code and ask _specific_ questions if you have any.

**Comment by luofan189** [comment]
Thanks for reply, here is the code, I am getting Cannot pipe. Not readable. error.

<code>
   s3Upload: function (req, fileParam, options, subdir, cb) {

```
options.maxBytes = sails.config.settings.MAX_FILE_UPLOAD_SIZE;

options.adapter = require('skipper-s3');

options.bucket = sails.config.s3.bucket;

if(subdir) {
  options.dirname = subdir;
}

options.key = sails.config.s3.accessKeyId;
options.secret = sails.config.s3.secretAccessKey;

var s3Adapter = require('skipper-s3')();
var s3Receiver = s3Adapter.receive();

s3Receiver
  .on('error', function(err) {
    res.serverError(err);
  })
  .on('finish', function() {
    res.json({
      message: 'File(s) uploaded successfully!'
    });
  });

var gm = require('gm');
var Writable = require('stream').Writable;

// Let's create a custom receiver
var receiver = new Writable({objectMode: true});
receiver._write = function(file, enc, cb) {
  gm(file).resize('200', '200').stream().pipe(options);
  cb();
};

receiver.pipe(s3Receiver);

req.file(fileParam).pipe(receiver);
```

  }
</code>

**Comment by bredikhin** [comment]
Hmm, ok, seems like it's not obvious. You'll have to go into the module code and find a way to use `gm` [here](https://github.com/bredikhin/skipper-thumbnail/blob/master/index.js#L5), then take the code from [here](https://github.com/bredikhin/sailsjs-skipper-thumbnail-example/blob/master/api/controllers/ImageController.js#L16) and replace disk receiver with S3 and thumbnail with your rewrite.

**Comment by luofan189** [comment]
That is the part I don't quite understand and don't know how do. I am trying to pipe s3Receiver but always get can not pipe, not readable.

**Comment by bredikhin** [comment]
You're getting 'cannot pipe / not readable' not because of S3 receiver, but because you `var receiver` is a writable stream, not readable. It should be a transform stream instead in order to do the resizing trick, like [here](https://github.com/bredikhin/skipper-thumbnail/blob/master/index.js). Maybe my explanations are kinda crooked, so feel free to ask [here](https://github.com/balderdashy/skipper/issues) or [here](https://github.com/balderdashy/skipper-s3/issues). Unfortunately, I just don't have any extra time to write you the exact code.

**Comment by luofan189** [comment]
I will try to do some learning on the transform stream. Thanks for your help on this!

**Comment by ArtKuz** [comment]
luofan189, can you realize how upload resize image with gm on s3? Have you code example?

**Comment by nhoctanker** [comment]
#bredikhin 
Hi . I'm new in sails and how to resize image wiht skipper gcs ( google cloud storege )  + Gm
